"""T1.a — counterfactual action-ranking probe (the QAS-specific RQ3(a) evidence).

Question: for a real circuit prefix s_t, can the WM RANK the legal next actions by the post-VQE
quality of the resulting continuation? (This is closer to the QAS contribution than generic
pairwise fidelity.) Also: does multi-step endpoint ranking hold as the imagined horizon grows?

Protocol (locked plan §5 T1.a):
  - Prefixes: held-out, generated by the FROZEN actor rolled to early/mid/late depth (policy-visited,
    independent of WM training, NOT from DAgger logs). P prefixes per depth bucket.
  - Candidates: up to M legal next actions at the prefix.
  - WM score: pred_logerr of each continuation prefix+[a] (batched via _encode_seeds; no VQE).
  - Ground truth: real error of prefix+[a] via _vqe_circuit (TRAINING-IDENTICAL VQE).
  - Per-prefix metrics: Spearman(pred, log10 real); top-k recall; normalized selected-action regret;
    actor-chosen-action percentile; WM-top-1 vs matched-random (multiple randoms, paired).
  - Aggregate: per-prefix rho -> rho_action = mean, bootstrap CI (NOT pooled across prefixes).
  - Horizon: endpoint ranking fidelity for H in {1,5,10,15} (pred vs real endpoint log-error).

Usage: python analysis/t1a_action_ranking.py <run_dir> [--device cpu|cuda:0] [--P 5] [--M 10]
       [--ckpts final|onset,final] [--horizons 1,5,10,15] [--tag t1a]
Writes <run_dir>/t1a_probe.json.
"""
import argparse
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT); sys.path.insert(0, os.path.join(ROOT, "phase2_surrogate"))
import numpy as np
import torch

from eval_policy_traces import _reload_dreamqas          # frozen reload (actor+wm+env), read-only
from imagine import _encode_seeds, _ens_std               # batched WM encode + ensemble disagreement
from circuit_rules import Shadow                           # stateless (Option C) legal mask

FLOOR = 1e-3   # mHa floor for log10


def _spearman(a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    if len(a) < 3 or np.std(a) == 0 or np.std(b) == 0:
        return np.nan
    ra = np.argsort(np.argsort(a)).astype(float); rb = np.argsort(np.argsort(b)).astype(float)
    ra -= ra.mean(); rb -= rb.mean()
    return float((ra * rb).sum() / np.sqrt((ra**2).sum() * (rb**2).sum()))


def _gen_prefix(r, depth, rng_seed):
    """Roll the frozen actor to `depth` gates using STATELESS Shadow legality (so the prefix is
    cleanly replayable by _vqe_circuit) + WM features. No env / no VQE here."""
    torch.manual_seed(rng_seed)
    hstate = r.wm.init_state(1, r.dev); feat = torch.zeros(1, r.cfg.wm_hidden, device=r.dev)
    sh = Shadow(r.N); acts = []
    for _ in range(depth):
        ill = set(sh.mask_indices() or [])
        if len(ill) >= r.A:
            break
        mask = torch.zeros(1, r.A, dtype=torch.bool, device=r.dev)
        if ill:
            mask[0, list(ill)] = True
        with torch.no_grad():
            a = int(r.actor(feat, mask).sample())
        sh.commit(r.trans[a]); acts.append(a)
        with torch.no_grad():
            feat, hstate, _ = r.wm.step(torch.tensor([a], device=r.dev), hstate)
    return acts


def _real_err(r, seq):
    """training-identical VQE of an action-sequence -> final true error (mHa).
    (_vqe_circuit now returns raw energies; te derived here — analysis MAY use E0.)"""
    Es, _ = r._vqe_circuit(list(seq), count_budget=False)
    return float(abs(r.env.min_energy - Es[-1]) * 1000.0) if Es else float("inf")


def _snap(env):
    """Snapshot exactly the mutable env state that step() touches, so we can evaluate many
    candidate next-actions from the SAME prefix without re-VQE-ing the prefix each time."""
    dm = getattr(env, "delta_mask", None)
    def _dup(x):
        return x.clone() if hasattr(x, "clone") else x.copy()
    return dict(state=env.state.clone(), step_counter=env.step_counter, moments=list(env.moments),
                op_history=[dict(o) for o in env.op_history],
                delta_mask=_dup(dm) if dm is not None else None,
                # illegal_actions is mutated in place by illegal_action_new() and NOT reset between
                # steps -> must be snapshotted or candidates corrupt each other.
                illegal_actions=[list(x) for x in env.illegal_actions],
                current_action=list(env.current_action) if env.current_action is not None else None)


def _restore(env, s):
    def _dup(x):
        return x.clone() if hasattr(x, "clone") else x.copy()
    env.state = s["state"].clone(); env.step_counter = s["step_counter"]
    env.moments = list(s["moments"]); env.op_history = [dict(o) for o in s["op_history"]]
    env.illegal_actions = [list(x) for x in s["illegal_actions"]]
    if s["delta_mask"] is not None:
        env.delta_mask = _dup(s["delta_mask"])
    env.current_action = list(s["current_action"]) if s["current_action"] is not None else None


def _wm_pred_logerr(r, seqs):
    """batched WM predicted log-error at the tip of each action-sequence -> np[len(seqs)]."""
    _, _, preds0 = _encode_seeds(r.wm, [list(s) for s in seqs], r.dev)   # [K, N]
    return preds0.mean(0).detach().cpu().numpy()


def probe_prefix(r, prefix, M, rng):
    # replay via the TRAINING path; `applied` = the actually-replayable prefix; env is left at its tip
    _, applied = r._vqe_circuit(list(prefix), count_budget=False)
    if len(applied) < 2:
        return None
    prefix = list(applied)
    env = r.env                                                        # now at the prefix tip
    snap = _snap(env)                                                  # snapshot BEFORE any mutation
    sh = Shadow(r.N)                                                   # stateless legal set (Option C)
    for a in prefix:
        sh.commit(r.trans[int(a)])
    ill = set(sh.mask_indices() or [])
    mask = torch.zeros(1, r.A, dtype=torch.bool, device=r.dev)
    if ill:
        mask[0, list(ill)] = True
    legal = [a for a in range(r.A) if a not in ill]
    if len(legal) < 3:
        return None
    cands = legal if len(legal) <= M else list(rng.choice(legal, M, replace=False))
    real = np.empty(len(cands), float)
    for i, a in enumerate(cands):                                     # one step per candidate (no prefix re-VQE)
        _restore(env, snap)
        env.step(list(r.trans[int(a)]), torch.tensor(0.0), train_flag=True)
        real[i] = abs(env.min_energy - env.energy) * 1000.0
    pred = _wm_pred_logerr(r, [prefix + [a] for a in cands])           # WM score (lower=better)
    lreal = np.log10(np.maximum(real, FLOOR))
    order_pred = np.argsort(pred); order_real = np.argsort(real)
    def recall_at(k):
        k = min(k, len(cands)); return len(set(order_pred[:k]) & set(order_real[:k])) / k
    wm_pick = int(order_pred[0])
    rng_lo, rng_hi = real.min(), real.max()
    regret = (real[wm_pick] - rng_lo) / (rng_hi - rng_lo) if rng_hi > rng_lo else 0.0
    # actor's own greedy action; percentile = fraction of candidates it beats on real error
    feat = _encode_seeds(r.wm, [prefix], r.dev)[1]                       # [1, hidden]
    with torch.no_grad():
        a_actor = int(r.actor(feat, mask).probs.argmax())
    actor_pct = float(np.mean(real < real[cands.index(a_actor)])) if a_actor in cands else float("nan")
    # matched-random: WM-top-1 vs several random candidates (paired, same budget)
    rand = rng.choice(len(cands), size=min(3, len(cands)), replace=False)
    wm_beats_rand = float(np.mean(real[wm_pick] <= real[rand]))
    return dict(rho=_spearman(pred, lreal), recall1=recall_at(1), recall3=recall_at(3),
                regret=float(regret), actor_pct=actor_pct, wm_beats_rand=wm_beats_rand,
                n_cand=len(cands))


def horizon_fidelity(r, prefixes, horizons, rng):
    """v2 (2026-07-18) — endpoint ranking fidelity vs H.

    v1 WAS AN ARTIFACT (retracted): prefixes were not normalized to env-replayable form and
    the continuation went through _vqe_circuit, whose illegal-action guard truncated most
    rollouts at/inside the prefix -- every H then measured the SAME endpoint, producing
    exactly flat, identical fidelity across H. v2 fixes both:
      - prefix := _vqe_circuit(prefix).applied  (same normalization probe_prefix uses);
      - the H continuation steps the REAL env under the env's own legality
        (env.illegal_action_new() mask -> every sampled action is applied by construction),
        with frozen-eval termination semantics (ignore accuracy-done, structural stops only,
        mirroring runner._rollout(run_to_max_depth=True)); WM features still drive the actor,
        so the imagination-policy semantics are preserved;
      - torch seed fixed PER PREFIX (not per H): the H sweep walks the SAME sampled path at
        increasing depths (nested endpoints), isolating the horizon effect from sampling noise;
      - bookkeeping: n, n_acc_done (accuracy-done ignored), version=2.
    """
    per_prefix = {}                                          # pi -> {H: (pred, real)}
    n_acc_done = {int(H): 0 for H in horizons}
    Hmax_all = max(int(H) for H in horizons)
    for pi, pre in enumerate(prefixes):
        Es0, applied = r._vqe_circuit(list(pre), count_budget=False)   # raw energies (new signature)
        if len(applied) < 2 or not Es0:
            continue
        snap = _snap(r.env)                                  # env is at the applied-prefix tip
        hs = r.wm.init_state(1, r.dev); ft = torch.zeros(1, r.cfg.wm_hidden, device=r.dev)
        for a in applied:                                    # WM state at the tip
            with torch.no_grad():
                ft, hs, _ = r.wm.step(torch.tensor([int(a)], device=r.dev), hs)
        per_prefix[pi] = {}
        torch.manual_seed(777000 + 131 * pi)                 # per-prefix stream -> nested paths over H
        _restore(r.env, snap)
        seq = list(applied); te_last = abs(r.env.min_energy - Es0[-1]) * 1000.0; ft_h, hs_h = ft, hs
        hit_acc_done = False
        for step_i in range(1, Hmax_all + 1):                # walk ONE path to Hmax, record at each H
            ill = set(r.env.illegal_action_new() or [])
            if len(ill) >= r.A or len(seq) >= r.env.num_layers:
                break                                        # structural termination only (eval semantics)
            mask = torch.zeros(1, r.A, dtype=torch.bool, device=r.dev)
            if ill:
                mask[0, list(ill)] = True
            with torch.no_grad():
                a = int(r.actor(ft_h, mask).sample())
            _, _, done, _ = r.env.step(list(r.trans[int(a)]), torch.tensor(0.0), train_flag=True)
            r.calib_vqe_calls += 1
            te_last = abs(r.env.min_energy - r.env.energy) * 1000.0
            seq.append(int(a))
            with torch.no_grad():
                ft_h, hs_h, _ = r.wm.step(torch.tensor([int(a)], device=r.dev), hs_h)
            hit_acc_done = hit_acc_done or bool(done)        # ignored (frozen-eval semantics), counted
            if step_i in [int(H) for H in horizons]:
                pred_end = float(_wm_pred_logerr(r, [list(seq)])[0])
                real_end = np.log10(max(float(te_last), FLOOR))
                per_prefix[pi][step_i] = (pred_end, real_end)
                if hit_acc_done:
                    n_acc_done[step_i] += 1
    out = {}
    for H in horizons:
        H = int(H)
        pts = [per_prefix[pi][H] for pi in per_prefix if H in per_prefix[pi]]
        preds = [p for p, _ in pts]; reals = [q for _, q in pts]
        out[str(H)] = dict(fidelity=_spearman(preds, reals), n=len(pts),
                           n_acc_done=n_acc_done[H], version=2)
    return out


def advantage_fidelity(r, prefixes, horizon, rng, beta):
    """The quantity the imagined policy gradient's CROSS-SEED BASELINE actually consumes.

    `imagine.py` builds its learning signal as
        reward_t = phi_t - phi_{t-1},      phi = -(mean_pred + beta * ensemble_std)
        R_t      = sum_k (gamma*lambda)^k reward_{t+k}          (lambda-return of INCREMENTS)
        adv_i,t  = R_i,t - mean_j R_j,t                          (baseline across the N seed states)
    so the per-step reward never contains an absolute value — any constant per-circuit bias cancels
    inside phi_t - phi_{t-1}. What the BASELINE does require is that the *magnitude of predicted
    improvement* be comparable ACROSS different seed circuits. No existing probe measures that:
    within-prefix rho fixes the prefix, endpoint fidelity compares absolute values, and Acc_pair
    draws arbitrary buffer pairs. This function measures it directly.

    Per prefix it walks ONE actor-sampled path through the REAL env (one real VQE per step, same
    protocol as `horizon_fidelity`) and records the per-step trace of
        phi_pred_t  = -(mean_pred + beta*std)   and   phi_pred0_t = -mean_pred   (beta=0 variant)
        phi_true_t  = -log10(real post-VQE error)
        disagree_t  = ensemble std (so the analysis can reproduce the confidence truncation)
    The traces are stored raw; returns/Spearman are computed downstream, which keeps gamma, lambda
    and the truncation rule as analysis choices rather than baking them in here.
    """
    out = []
    for pi, pre in enumerate(prefixes):
        Es0, applied = r._vqe_circuit(list(pre), count_budget=False)
        if len(applied) < 2 or not Es0:
            continue
        hs = r.wm.init_state(1, r.dev)
        ft = torch.zeros(1, r.cfg.wm_hidden, device=r.dev)
        for a in applied:
            with torch.no_grad():
                ft, hs, ph = r.wm.step(torch.tensor([int(a)], device=r.dev), hs)
        pm = float(ph.mean(0)[0]); ps = float(_ens_std(ph)[0])
        tr = dict(phi_pred=[-(pm + beta * ps)], phi_pred_b0=[-pm], disagree=[ps],
                  phi_true=[-float(np.log10(max(abs(r.env.min_energy - Es0[-1]) * 1000.0, FLOOR)))],
                  seed_len=len(applied))
        torch.manual_seed(555000 + 131 * pi)          # own stream: never perturbs horizon_fidelity's
        seq = list(applied)
        for _ in range(horizon):
            ill = set(r.env.illegal_action_new() or [])
            if len(ill) >= r.A or len(seq) >= r.env.num_layers:
                break
            mask = torch.zeros(1, r.A, dtype=torch.bool, device=r.dev)
            if ill:
                mask[0, list(ill)] = True
            with torch.no_grad():
                a = int(r.actor(ft, mask).sample())
            r.env.step(list(r.trans[int(a)]), torch.tensor(0.0), train_flag=True)
            r.calib_vqe_calls += 1
            seq.append(int(a))
            with torch.no_grad():
                ft, hs, ph = r.wm.step(torch.tensor([int(a)], device=r.dev), hs)
            pm = float(ph.mean(0)[0]); ps = float(_ens_std(ph)[0])
            tr["phi_pred"].append(-(pm + beta * ps))
            tr["phi_pred_b0"].append(-pm)
            tr["disagree"].append(ps)
            tr["phi_true"].append(
                -float(np.log10(max(abs(r.env.min_energy - r.env.energy) * 1000.0, FLOOR))))
        if len(tr["phi_pred"]) >= 2:
            out.append(tr)
    return dict(traces=out, beta=float(beta), n=len(out), version=1)


def run(run_dir, device, P, M, ckpt_sel, horizons, tag, start_depths=(), adv_fid=0):
    cks = sorted(glob.glob(f"{run_dir}/ckpt/ep*.pt"), key=lambda p: int(os.path.basename(p)[2:-3]))
    if not cks:
        print(f"[t1a] no ckpts in {run_dir}"); return
    eps = [int(os.path.basename(p)[2:-3]) for p in cks]
    final_ck = cks[-1]
    onset_ck = cks[max(0, len(cks) // 5)]                      # ~20% into training ~ imagination onset
    targets = {}
    if "final" in ckpt_sel:
        targets["final"] = final_ck
    if "onset" in ckpt_sel:
        targets["onset"] = onset_ck
    if "quarter" in ckpt_sel:
        # 1/4-budget checkpoint (aligns the horizon probe with the paper's 1/4-budget operating
        # point AND keeps molecules comparable even when some ran to full budget). Full episode
        # budget = real_eps_per_iter * n_iterations; pick the ckpt nearest 1/4 of it.
        _cfg0 = torch.load(final_ck, map_location="cpu", weights_only=False).get("cfg", {})
        q_ep = int(_cfg0.get("real_eps_per_iter", 4)) * int(_cfg0.get("n_iterations", 0)) // 4
        targets["quarter"] = min(cks, key=lambda p: abs(int(os.path.basename(p)[2:-3]) - q_ep))
        print(f"[t1a] {os.path.basename(run_dir)} quarter target ep~{q_ep} -> "
              f"{os.path.basename(targets['quarter'])}")
    if "wmstart" in ckpt_sel:
        # WM-training onset = the imagination warm-up boundary (warmup_eps, default 500): the first
        # checkpoint at/after the WM begins guiding the policy. Principled "early" point (not a
        # barely-initialised strawman) where action-ranking has had ~no training signal yet.
        _cfg0 = torch.load(final_ck, map_location="cpu", weights_only=False).get("cfg", {})
        w = int(_cfg0.get("warmup_eps", 500))
        targets["wmstart"] = min(cks, key=lambda p: abs(int(os.path.basename(p)[2:-3]) - w))
        print(f"[t1a] {os.path.basename(run_dir)} wmstart target ep~{w} -> "
              f"{os.path.basename(targets['wmstart'])}")
    for sel in ckpt_sel:
        # "early<pct>" checkpoint at ~pct% of the FULL episode budget (budget-relative, molecule-
        # comparable; replaces the index-based cks[len//5] "onset" which landed at ~0.5% of training).
        # Full budget = real_eps_per_iter * n_iterations; pick the ckpt nearest pct/100 of it.
        if not (sel.startswith("early") and sel[5:].isdigit()):
            continue
        frac = int(sel[5:]) / 100.0
        _cfg0 = torch.load(final_ck, map_location="cpu", weights_only=False).get("cfg", {})
        e_ep = int(int(_cfg0.get("real_eps_per_iter", 4)) * int(_cfg0.get("n_iterations", 0)) * frac)
        targets[sel] = min(cks, key=lambda p: abs(int(os.path.basename(p)[2:-3]) - e_ep))
        print(f"[t1a] {os.path.basename(run_dir)} {sel} target ep~{e_ep} -> "
              f"{os.path.basename(targets[sel])}")
    if not targets:
        targets = {"final": final_ck}
    result = {"run": os.path.basename(run_dir), "P": P, "M": M}
    rng = np.random.default_rng(12345)
    for name, ckp in targets.items():
        ck = torch.load(ckp, map_location="cpu", weights_only=False)
        r, seed = _reload_dreamqas(ck, device)
        r.wm.eval(); r.actor.eval()
        maxd = r.env.num_layers
        depths = {"early": max(2, maxd // 6), "mid": maxd // 2, "late": max(2, maxd - 4)}
        # action-ranking prefixes across depth buckets (early/mid/late)
        prefixes = []
        for bi, (bname, d) in enumerate(depths.items()):
            for j in range(P):
                pre = _gen_prefix(r, d, rng_seed=1000 * bi + 7 * j + int(seed))
                if len(pre) >= 2:
                    prefixes.append(pre)
        # horizon sweep needs SHALLOW prefixes with room for H more gates (else all H hit the depth cap);
        # use a fixed ~15 so the across-prefix Spearman has resolution.
        sd = max(2, maxd // 4)
        shallow = [pre for j in range(15)
                   for pre in [_gen_prefix(r, sd, rng_seed=99000 + 7 * j + int(seed))] if len(pre) >= 2]
        rows = [pp for pp in (probe_prefix(r, pre, M, rng) for pre in prefixes) if pp]
        agg = {}
        if rows:
            rhos = np.array([x["rho"] for x in rows if not np.isnan(x["rho"])])
            # bootstrap CI on mean per-prefix rho
            if len(rhos) >= 3:
                bs = [np.mean(rng.choice(rhos, len(rhos), replace=True)) for _ in range(2000)]
                ci = (float(np.percentile(bs, 2.5)), float(np.percentile(bs, 97.5)))
            else:
                ci = (np.nan, np.nan)
            agg = dict(n_prefix=len(rows), rho_action=float(np.mean(rhos)), rho_ci=ci,
                       recall1=float(np.mean([x["recall1"] for x in rows])),
                       recall3=float(np.mean([x["recall3"] for x in rows])),
                       regret=float(np.mean([x["regret"] for x in rows])),
                       wm_beats_rand=float(np.mean([x["wm_beats_rand"] for x in rows])))
        hz = horizon_fidelity(r, shallow, horizons, rng) if horizons else {}
        result[name] = {"agg": agg, "horizon": hz, "ck_ep": int(os.path.basename(ckp)[2:-3])}
        # --- OPTIONAL: repeat the sweep from EXTRA start depths (default off -> legacy behaviour) ---
        # Endpoint depth == start_depth + H, so with one start depth the two are indistinguishable and
        # `horizon` can only be read as accuracy-vs-depth. Sweeping several start depths makes ONE
        # endpoint depth reachable via different H (e.g. sd=10,H=15 and sd=20,H=5 both land at 25),
        # which is what tests whether endpoint depth ALONE explains the curve or the circuit population
        # matters too. Stored under separate `horizon_sd<d>` keys; `horizon` above is never touched.
        for d0 in (start_depths or []):
            if d0 + max(horizons) > maxd:
                print(f"[t1a] skip start_depth={d0}: {d0}+{max(horizons)} exceeds ansatz cap {maxd}")
                continue
            sh = [pre for j in range(15)
                  for pre in [_gen_prefix(r, d0, rng_seed=99000 + 7 * j + int(seed))] if len(pre) >= 2]
            if not sh:
                continue
            result[name][f"horizon_sd{d0}"] = horizon_fidelity(r, sh, horizons, rng)
            f1 = result[name][f"horizon_sd{d0}"].get(str(horizons[0]), {}).get("fidelity", float("nan"))
            fN = result[name][f"horizon_sd{d0}"].get(str(horizons[-1]), {}).get("fidelity", float("nan"))
            print(f"[t1a] {os.path.basename(run_dir)} [{name}] start_depth={d0} "
                  f"(endpoints {d0 + horizons[0]}..{d0 + horizons[-1]}): "
                  f"fid H{horizons[0]}={f1:.3f} -> H{horizons[-1]}={fN:.3f}", flush=True)
        # --- OPTIONAL: advantage-fidelity trace (default off -> legacy behaviour) ---
        if adv_fid:
            beta = float(getattr(r.cfg, "pessimism_beta", 1.0))
            result[name]["advfid"] = advantage_fidelity(r, shallow, int(adv_fid), rng, beta)
            print(f"[t1a] {os.path.basename(run_dir)} [{name}] advfid: "
                  f"{result[name]['advfid']['n']} traces x {adv_fid} steps (beta={beta})", flush=True)
        print(f"[t1a] {os.path.basename(run_dir)} [{name}] rho_action={agg.get('rho_action', float('nan')):.3f} "
              f"regret={agg.get('regret', float('nan')):.3f} recall@1={agg.get('recall1', float('nan')):.3f} "
              f"wm>rand={agg.get('wm_beats_rand', float('nan')):.3f} n={agg.get('n_prefix', 0)}", flush=True)
        del r
    out = f"{run_dir}/t1a_probe.json"
    if os.path.exists(out):
        # MERGE at SUB-KEY granularity. A top-level `prev.update(result)` keeps other selectors
        # (onset/quarter/final) but REPLACES the whole selector dict, so re-running one selector with
        # a narrower set of sub-probes silently deletes the rest — e.g. `--horizons "" --adv_fidelity 10`
        # wiped an existing final.horizon_sd* set. Merge per selector, and never let an empty result
        # overwrite non-empty stored data.
        try:
            prev = json.load(open(out))
            for k, v in result.items():
                if isinstance(v, dict) and isinstance(prev.get(k), dict):
                    for sk, sv in v.items():
                        if sv or not prev[k].get(sk):     # empty sub-result never clobbers stored data
                            prev[k][sk] = sv
                else:
                    prev[k] = v
            result = prev
        except Exception:
            pass
    json.dump(result, open(out, "w"), indent=2)
    print(f"[t1a] wrote {out}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("run_dir")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--P", type=int, default=5)
    ap.add_argument("--M", type=int, default=10)
    ap.add_argument("--ckpts", default="final")
    ap.add_argument("--horizons", default="1,5,10,15")
    ap.add_argument("--tag", default="t1a")
    ap.add_argument("--start_depths", default="",
                    help="EXTRA prefix start depths for the horizon sweep, comma-separated (e.g. "
                         "'10,15,20'). Empty (default) = legacy behaviour, one sweep at num_layers//4. "
                         "Each extra depth writes a separate `horizon_sd<d>` key; `horizon` is never "
                         "overwritten. Use overlapping sets so one endpoint depth is reached via "
                         "different H — that is what separates endpoint depth from circuit population.")
    ap.add_argument("--adv_fidelity", type=int, default=0,
                    help="If >0, additionally record an ADVANTAGE-FIDELITY trace of this many actor "
                         "steps per prefix: the per-step (predicted phi, true phi) pair that the "
                         "imagined policy gradient's cross-seed baseline consumes. 0 (default) = off, "
                         "legacy behaviour. Stored under the `advfid` key; nothing else is touched.")
    a = ap.parse_args()
    hz = [int(x) for x in a.horizons.split(",")] if a.horizons.strip() else []
    sd = [int(x) for x in a.start_depths.split(",") if x.strip()] if a.start_depths.strip() else []
    run(a.run_dir, a.device, a.P, a.M, a.ckpts.split(","), hz, a.tag, sd, a.adv_fidelity)
